// Generated by CoffeeScript 1.12.7

/* Multi line comment */

(function() {
  var csOutput, name;

  name = "Phil";

  csOutput = document.getElementById("csoutput");

  csOutput.innerHTML = "Hello " + name;

}).call(this);
