// Generated by CoffeeScript 1.12.7

/*
Multiline Comment
 */

(function() {
  var aString, age, areYouHappy, balance, chicken, chickenName, childAge, coat, csOutput, fName, gloves, hat, hsGrad, i, lName, largeNumStr, largestNum, len, longString, name, precisionTest, randNum, schoolGrade, smallNumStr, smallestNum, strArray, votingAge, x;

  name = "Phil";

  csOutput = document.getElementById("csoutput");

  csOutput.innerHTML = "Hello " + name + "<br>";

  aString = "I'm a String";

  if (typeof aString === 'string') {
    csOutput.insertAdjacentHTML('beforeend', 'aString is a String<br>');
  }

  largestNum = Number.MAX_VALUE;

  smallestNum = Number.MIN_VALUE;

  largeNumStr = "The largest number is " + largestNum + "<br>";

  smallNumStr = "The smallest number is " + smallestNum + "<br>";

  csOutput.insertAdjacentHTML('beforeend', largeNumStr);

  csOutput.insertAdjacentHTML('beforeend', smallNumStr);

  areYouHappy = false;

  if (typeof areYouHappy === 'boolean') {
    csOutput.insertAdjacentHTML('beforeend', 'areYouHappy is a Boolean<br>');
  }

  csOutput.insertAdjacentHTML('beforeend', "5 + 2 = " + (5 + 2) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "5 - 2 = " + (5 - 2) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "5 * 2 = " + (5 * 2) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "5 / 2 = " + (5 / 2) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "5 % 2 = " + (5 % 2) + "<br>");

  precisionTest = 0.1000000000000001;

  csOutput.insertAdjacentHTML('beforeend', "Precision : " + (precisionTest + 0.10000000000000011) + "<br>");

  balance = 1563.87;

  csOutput.insertAdjacentHTML('beforeend', "Monthly Payment = " + ((balance / 12).toFixed(2)) + "<br>");

  randNum = 5;

  csOutput.insertAdjacentHTML('beforeend', "randNum++ = " + (randNum++) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "++randNum = " + (++randNum) + "<br>");

  randNum = 5;

  csOutput.insertAdjacentHTML('beforeend', "randNum-- = " + (randNum--) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "--randNum = " + (--randNum) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "3 + 2 * 5 = " + (3 + 2 * 5) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "(3 + 2) * 5 = " + ((3 + 2) * 5) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.E = " + Math.E + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.PI = " + Math.PI + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.abs(-8) = " + (Math.abs(-8)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.cbrt(1000) = " + (Math.cbrt(1000)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.ceil(6.45) = " + (Math.ceil(6.45)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.floor(6.45) = " + (Math.floor(6.45)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.round(6.45) = " + (Math.round(6.45)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.log(10) = " + (Math.log(10)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.log10(10) = " + (Math.log10(10)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.pow(4,2) = " + (Math.pow(4, 2)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Math.sqrt(1000) = " + (Math.sqrt(1000)) + "<br>");

  randNum = Math.floor(Math.random() * 100) + 1;

  csOutput.insertAdjacentHTML('beforeend', "Random Number = " + randNum + "<br>");

  fName = "Derek";

  lName = "Banas";

  csOutput.insertAdjacentHTML('beforeend', fName + " " + lName + "<br>");

  longString = "This is a long string that goes on forever";

  csOutput.insertAdjacentHTML('beforeend', "String Length : " + longString.length + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Index of string : " + (longString.indexOf("goes")) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Index 8 : " + (longString.charAt(8)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "Word at 27 : " + (longString.slice(27, 31)) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', "After 27 : " + (longString.slice(27)) + "<br>");

  longString = longString.replace("forever", "and on forever   ");

  csOutput.insertAdjacentHTML('beforeend', "New String : " + longString + "<br>");

  strArray = longString.split(" ");

  for (i = 0, len = strArray.length; i < len; i++) {
    x = strArray[i];
    csOutput.insertAdjacentHTML('beforeend', x + "<br>");
  }

  longString = longString.trim();

  csOutput.insertAdjacentHTML('beforeend', (longString.toUpperCase()) + "<br>");

  csOutput.insertAdjacentHTML('beforeend', (longString.toLowerCase()) + "<br>");

  age = 3;

  if (age >= 18) {
    csOutput.insertAdjacentHTML('beforeend', 'You can Vote<br>');
    if (age >= 16) {
      csOutput.insertAdjacentHTML('beforeend', 'You can Drive also<br>');
    }
  } else if (age >= 16) {
    csOutput.insertAdjacentHTML('beforeend', 'You can Drive<br>');
  } else {
    csOutput.insertAdjacentHTML('beforeend', 'You\'ll be 16 soon<br>');
  }

  if (!(age >= 19)) {
    csOutput.insertAdjacentHTML('beforeend', 'You are in school<br>');
  } else {
    csOutput.insertAdjacentHTML('beforeend', 'You may go to college<br>');
  }

  hsGrad = true;

  if (!(age > 4) || (age > 65)) {
    csOutput.insertAdjacentHTML('beforeend', 'You don\'t go to school<br>');
  } else if ((age >= 5) && (age <= 6)) {
    csOutput.insertAdjacentHTML('beforeend', 'Go to Kindergarten<br>');
  } else if ((age > 6) && (age <= 18)) {
    schoolGrade = "Go to Grade " + (age - 5) + "<br>";
    csOutput.insertAdjacentHTML('beforeend', schoolGrade);
  } else {
    csOutput.insertAdjacentHTML('beforeend', 'Go to Work<br>');
  }

  votingAge = age > 18 ? true : false;

  csOutput.insertAdjacentHTML('beforeend', "Can Vote : " + votingAge + "<br>");

  childAge = 7;

  switch (childAge) {
    case 5:
      csOutput.insertAdjacentHTML('beforeend', 'Go to Kindergarten<br>');
      break;
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
      csOutput.insertAdjacentHTML('beforeend', 'Go to Elementary School<br>');
      break;
    default:
      csOutput.insertAdjacentHTML('beforeend', 'Go to Someplace<br>');
  }

  if (age != null) {
    csOutput.insertAdjacentHTML('beforeend', age + " years old<br>");
  }

  chicken = null;

  chickenName = chicken != null ? chicken : "Fred";

  csOutput.insertAdjacentHTML('beforeend', "Chickens Name : " + chickenName + "<br>");

  hat = "Winter Hat";

  coat = "Winter Coat";

  gloves = null;

  if ((hat != null) && (coat != null)) {
    csOutput.insertAdjacentHTML('beforeend', hat + " " + coat + " " + (gloves != null ? gloves : '?') + "<br>");
  }

}).call(this);
